name: Example Workflow for Environment Files

on: push

jobs:
  set_and_use_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: sex
        run: |
          printf "WORKING\nA\x0bB\x0cC\x1cD\x1dE\x1eF\x85G\u2028H\u2029I"
