name: Example Workflow for Environment Files

on: push

jobs:
  set_and_use_env_vars:
    runs-on: ubuntu-latest
    steps:
      - name: sex
        run: |
          echo -e "::warning::sex\n::error::wahhhhh"
